### ISSUE TITLE
Update babel-eslint peer dependency

### ISSUE THREAD

**Issue by shaun-mac** [SatelCreative/eslint-plugin#2]
I'm updating dependencies on Tally, and it looks like the latest `babel-eslint` release is 10.0.2. This causes an 'incorrect peer dependency' error with `@satel/eslint-config-react`. Would be good if the peer dependency is updated to allow for this newer version.

Also happy to jump on this if it's a simple fix!

**Comment by qw-in** [comment]
I'll have a look at updating this, been meaning to add the typescript config as well

**Comment by qw-in** [comment]
Dropped the need for it in `@satel/eslint-config-react@2.0.0`. The eslint parser seems to work fine on it's own now
